project:
  name: Uploader extProcces
  debug: true
  environment: development

database:
  host: localhost
  port: 5432
  user: user
  password: passuser
  name: queue_work
  sslmode: disable
  migrations: migrations
  driver: pgx

telegramm:
  token: mToken
  chat_id_error: 654848

gitlab:
  url: https://gitlabaddr.com
  project_url: nameProject 

rest:
  port: 5050
  pathfile: "/"